# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/media/aleksejs/DataHDD/work/codes/comp-neuro/analysis-tracking/dlc-scripts/scripts/video_processing/video_process_gui_files/ffmpeg_wrapper.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_FFMPEG_WRAPPER(object):
    def setupUi(self, FFMPEG_WRAPPER):
        FFMPEG_WRAPPER.setObjectName("FFMPEG_WRAPPER")
        FFMPEG_WRAPPER.resize(1921, 1284)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(FFMPEG_WRAPPER.sizePolicy().hasHeightForWidth())
        FFMPEG_WRAPPER.setSizePolicy(sizePolicy)
        self.centralWidget = QtWidgets.QWidget(FFMPEG_WRAPPER)
        self.centralWidget.setObjectName("centralWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralWidget)
        self.horizontalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        self.tabWidget.setObjectName("tabWidget")
        self.infoCrawlTab = QtWidgets.QWidget()
        self.infoCrawlTab.setObjectName("infoCrawlTab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.infoCrawlTab)
        self.verticalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.infoCrawlGetRootButton = QtWidgets.QPushButton(self.infoCrawlTab)
        self.infoCrawlGetRootButton.setObjectName("infoCrawlGetRootButton")
        self.horizontalLayout_4.addWidget(self.infoCrawlGetRootButton)
        self.infoCrawlProgressBar = QtWidgets.QProgressBar(self.infoCrawlTab)
        self.infoCrawlProgressBar.setEnabled(False)
        self.infoCrawlProgressBar.setProperty("value", 0)
        self.infoCrawlProgressBar.setObjectName("infoCrawlProgressBar")
        self.horizontalLayout_4.addWidget(self.infoCrawlProgressBar)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.infoCrawlTableWidget = QtWidgets.QTableWidget(self.infoCrawlTab)
        self.infoCrawlTableWidget.setAutoScroll(False)
        self.infoCrawlTableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.infoCrawlTableWidget.setObjectName("infoCrawlTableWidget")
        self.infoCrawlTableWidget.setColumnCount(7)
        self.infoCrawlTableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.infoCrawlTableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.infoCrawlTableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.infoCrawlTableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.infoCrawlTableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.infoCrawlTableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.infoCrawlTableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.infoCrawlTableWidget.setHorizontalHeaderItem(6, item)
        self.infoCrawlTableWidget.horizontalHeader().setCascadingSectionResizes(True)
        self.infoCrawlTableWidget.horizontalHeader().setStretchLastSection(True)
        self.infoCrawlTableWidget.verticalHeader().setVisible(False)
        self.infoCrawlTableWidget.verticalHeader().setCascadingSectionResizes(False)
        self.infoCrawlTableWidget.verticalHeader().setStretchLastSection(True)
        self.verticalLayout_2.addWidget(self.infoCrawlTableWidget)
        self.tabWidget.addTab(self.infoCrawlTab, "")
        self.vidoeCompressTab = QtWidgets.QWidget()
        self.vidoeCompressTab.setObjectName("vidoeCompressTab")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.vidoeCompressTab)
        self.horizontalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.mainModeComboBox = QtWidgets.QComboBox(self.vidoeCompressTab)
        self.mainModeComboBox.setObjectName("mainModeComboBox")
        self.mainModeComboBox.addItem("")
        self.mainModeComboBox.addItem("")
        self.mainModeComboBox.addItem("")
        self.verticalLayout_3.addWidget(self.mainModeComboBox)
        self.mainEncodingComboBox = QtWidgets.QComboBox(self.vidoeCompressTab)
        self.mainEncodingComboBox.setObjectName("mainEncodingComboBox")
        self.mainEncodingComboBox.addItem("")
        self.mainEncodingComboBox.addItem("")
        self.mainEncodingComboBox.addItem("")
        self.verticalLayout_3.addWidget(self.mainEncodingComboBox)
        self.mainGrayscaleCheckBox = QtWidgets.QCheckBox(self.vidoeCompressTab)
        self.mainGrayscaleCheckBox.setObjectName("mainGrayscaleCheckBox")
        self.verticalLayout_3.addWidget(self.mainGrayscaleCheckBox)
        self.mainLosslessCheckBox = QtWidgets.QCheckBox(self.vidoeCompressTab)
        self.mainLosslessCheckBox.setObjectName("mainLosslessCheckBox")
        self.verticalLayout_3.addWidget(self.mainLosslessCheckBox)
        self.frame = QtWidgets.QFrame(self.vidoeCompressTab)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.mainQuality1Label = QtWidgets.QLabel(self.frame)
        self.mainQuality1Label.setObjectName("mainQuality1Label")
        self.horizontalLayout.addWidget(self.mainQuality1Label)
        self.mainQuality2Label = QtWidgets.QLabel(self.frame)
        self.mainQuality2Label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.mainQuality2Label.setObjectName("mainQuality2Label")
        self.horizontalLayout.addWidget(self.mainQuality2Label)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.mainQualityCRFSlider = QtWidgets.QSlider(self.frame)
        self.mainQualityCRFSlider.setAutoFillBackground(True)
        self.mainQualityCRFSlider.setMaximum(51)
        self.mainQualityCRFSlider.setOrientation(QtCore.Qt.Horizontal)
        self.mainQualityCRFSlider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.mainQualityCRFSlider.setTickInterval(10)
        self.mainQualityCRFSlider.setObjectName("mainQualityCRFSlider")
        self.verticalLayout.addWidget(self.mainQualityCRFSlider)
        self.verticalLayout_3.addWidget(self.frame)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.mainSourceButton = QtWidgets.QPushButton(self.vidoeCompressTab)
        self.mainSourceButton.setMinimumSize(QtCore.QSize(200, 0))
        self.mainSourceButton.setObjectName("mainSourceButton")
        self.verticalLayout_4.addWidget(self.mainSourceButton)
        self.mainTargetButton = QtWidgets.QPushButton(self.vidoeCompressTab)
        self.mainTargetButton.setObjectName("mainTargetButton")
        self.verticalLayout_4.addWidget(self.mainTargetButton)
        self.mainConvertButton = QtWidgets.QPushButton(self.vidoeCompressTab)
        self.mainConvertButton.setObjectName("mainConvertButton")
        self.verticalLayout_4.addWidget(self.mainConvertButton)
        self.horizontalLayout_3.addLayout(self.verticalLayout_4)
        self.tabWidget.addTab(self.vidoeCompressTab, "")
        self.horizontalLayout_2.addWidget(self.tabWidget)
        FFMPEG_WRAPPER.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(FFMPEG_WRAPPER)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1921, 29))
        self.menuBar.setObjectName("menuBar")
        FFMPEG_WRAPPER.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(FFMPEG_WRAPPER)
        self.mainToolBar.setObjectName("mainToolBar")
        FFMPEG_WRAPPER.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(FFMPEG_WRAPPER)
        self.statusBar.setObjectName("statusBar")
        FFMPEG_WRAPPER.setStatusBar(self.statusBar)

        self.retranslateUi(FFMPEG_WRAPPER)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(FFMPEG_WRAPPER)

    def retranslateUi(self, FFMPEG_WRAPPER):
        _translate = QtCore.QCoreApplication.translate
        FFMPEG_WRAPPER.setWindowTitle(_translate("FFMPEG_WRAPPER", "FFMPEG_WRAPPER"))
        self.infoCrawlGetRootButton.setText(_translate("FFMPEG_WRAPPER", "Select Parent Directory..."))
        self.infoCrawlTableWidget.setSortingEnabled(True)
        item = self.infoCrawlTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("FFMPEG_WRAPPER", "Extension"))
        item = self.infoCrawlTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("FFMPEG_WRAPPER", "Number of Files"))
        item = self.infoCrawlTableWidget.horizontalHeaderItem(2)
        item.setText(_translate("FFMPEG_WRAPPER", "Total Size"))
        item = self.infoCrawlTableWidget.horizontalHeaderItem(3)
        item.setText(_translate("FFMPEG_WRAPPER", "Shape"))
        item = self.infoCrawlTableWidget.horizontalHeaderItem(4)
        item.setText(_translate("FFMPEG_WRAPPER", "nFrames"))
        item = self.infoCrawlTableWidget.horizontalHeaderItem(5)
        item.setText(_translate("FFMPEG_WRAPPER", "FPS"))
        item = self.infoCrawlTableWidget.horizontalHeaderItem(6)
        item.setText(_translate("FFMPEG_WRAPPER", "codec"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.infoCrawlTab), _translate("FFMPEG_WRAPPER", "infoCrawl"))
        self.mainModeComboBox.setItemText(0, _translate("FFMPEG_WRAPPER", "--- select mode ---"))
        self.mainModeComboBox.setItemText(1, _translate("FFMPEG_WRAPPER", "Single Video"))
        self.mainModeComboBox.setItemText(2, _translate("FFMPEG_WRAPPER", "Folder Crawler"))
        self.mainEncodingComboBox.setItemText(0, _translate("FFMPEG_WRAPPER", "--- target encoding ---"))
        self.mainEncodingComboBox.setItemText(1, _translate("FFMPEG_WRAPPER", "AVI"))
        self.mainEncodingComboBox.setItemText(2, _translate("FFMPEG_WRAPPER", "MP4 (H265)"))
        self.mainGrayscaleCheckBox.setText(_translate("FFMPEG_WRAPPER", "Grayscale"))
        self.mainLosslessCheckBox.setText(_translate("FFMPEG_WRAPPER", "Lossless"))
        self.mainQuality1Label.setText(_translate("FFMPEG_WRAPPER", "Quality (CRF)"))
        self.mainQuality2Label.setText(_translate("FFMPEG_WRAPPER", "0"))
        self.mainSourceButton.setText(_translate("FFMPEG_WRAPPER", "Select Source"))
        self.mainTargetButton.setText(_translate("FFMPEG_WRAPPER", "Select Target"))
        self.mainConvertButton.setText(_translate("FFMPEG_WRAPPER", "Convert"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.vidoeCompressTab), _translate("FFMPEG_WRAPPER", "Tab 1"))

