# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/media/aleksejs/DataHDD/work/codes/image-analysis/behavioural/dlc-scripts/dlc_serv_gui/dlc_serv_gui/dlcgui.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_dlcgui(object):
    def setupUi(self, dlcgui):
        dlcgui.setObjectName("dlcgui")
        dlcgui.resize(1222, 1024)
        self.centralWidget = QtWidgets.QWidget(dlcgui)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.mainTabWidget = QtWidgets.QTabWidget(self.centralWidget)
        self.mainTabWidget.setObjectName("mainTabWidget")
        self.markTab = QtWidgets.QWidget()
        self.markTab.setObjectName("markTab")
        self.gridLayout = QtWidgets.QGridLayout(self.markTab)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.markTabWidget = QtWidgets.QTabWidget(self.markTab)
        self.markTabWidget.setObjectName("markTabWidget")
        self.markPathsTab = QtWidgets.QWidget()
        self.markPathsTab.setObjectName("markPathsTab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.markPathsTab)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pathsNetworkVideoLabel = QtWidgets.QLabel(self.markPathsTab)
        self.pathsNetworkVideoLabel.setObjectName("pathsNetworkVideoLabel")
        self.gridLayout_3.addWidget(self.pathsNetworkVideoLabel, 1, 2, 1, 1)
        self.pathsLocalButton = QtWidgets.QPushButton(self.markPathsTab)
        self.pathsLocalButton.setObjectName("pathsLocalButton")
        self.gridLayout_3.addWidget(self.pathsLocalButton, 0, 0, 1, 1)
        self.pathsNetworkVideoLineEdit = QtWidgets.QLineEdit(self.markPathsTab)
        self.pathsNetworkVideoLineEdit.setObjectName("pathsNetworkVideoLineEdit")
        self.gridLayout_3.addWidget(self.pathsNetworkVideoLineEdit, 1, 1, 1, 1)
        self.pathsLocalLabel = QtWidgets.QLabel(self.markPathsTab)
        self.pathsLocalLabel.setObjectName("pathsLocalLabel")
        self.gridLayout_3.addWidget(self.pathsLocalLabel, 0, 2, 1, 1)
        self.pathsLocalLineEdit = QtWidgets.QLineEdit(self.markPathsTab)
        self.pathsLocalLineEdit.setObjectName("pathsLocalLineEdit")
        self.gridLayout_3.addWidget(self.pathsLocalLineEdit, 0, 1, 1, 1)
        self.pathsNetworkVideoButton = QtWidgets.QPushButton(self.markPathsTab)
        self.pathsNetworkVideoButton.setObjectName("pathsNetworkVideoButton")
        self.gridLayout_3.addWidget(self.pathsNetworkVideoButton, 1, 0, 1, 1)
        self.pathsImportButton = QtWidgets.QPushButton(self.markPathsTab)
        self.pathsImportButton.setObjectName("pathsImportButton")
        self.gridLayout_3.addWidget(self.pathsImportButton, 2, 0, 1, 1)
        self.pathsImportLineEdit = QtWidgets.QLineEdit(self.markPathsTab)
        self.pathsImportLineEdit.setObjectName("pathsImportLineEdit")
        self.gridLayout_3.addWidget(self.pathsImportLineEdit, 2, 1, 1, 1)
        self.pathsImportLabel = QtWidgets.QLabel(self.markPathsTab)
        self.pathsImportLabel.setObjectName("pathsImportLabel")
        self.gridLayout_3.addWidget(self.pathsImportLabel, 2, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_3)
        self.pathsImportPathsButton = QtWidgets.QPushButton(self.markPathsTab)
        self.pathsImportPathsButton.setObjectName("pathsImportPathsButton")
        self.verticalLayout.addWidget(self.pathsImportPathsButton)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.markTabWidget.addTab(self.markPathsTab, "")
        self.markParamsTab = QtWidgets.QWidget()
        self.markParamsTab.setObjectName("markParamsTab")
        self.gridLayoutWidget = QtWidgets.QWidget(self.markParamsTab)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(120, 50, 471, 351))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_2.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.paramSelectionLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.paramSelectionLabel.setObjectName("paramSelectionLabel")
        self.gridLayout_2.addWidget(self.paramSelectionLabel, 3, 0, 1, 1)
        self.paramSelectionComboBox = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.paramSelectionComboBox.setObjectName("paramSelectionComboBox")
        self.paramSelectionComboBox.addItem("")
        self.paramSelectionComboBox.addItem("")
        self.gridLayout_2.addWidget(self.paramSelectionComboBox, 3, 1, 1, 1)
        self.paramNameLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.paramNameLabel.setObjectName("paramNameLabel")
        self.gridLayout_2.addWidget(self.paramNameLabel, 0, 0, 1, 1)
        self.paramDataLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.paramDataLabel.setObjectName("paramDataLabel")
        self.gridLayout_2.addWidget(self.paramDataLabel, 1, 0, 1, 1)
        self.paramNameLineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.paramNameLineEdit.setObjectName("paramNameLineEdit")
        self.gridLayout_2.addWidget(self.paramNameLineEdit, 0, 1, 1, 1)
        self.paramDataLineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.paramDataLineEdit.setObjectName("paramDataLineEdit")
        self.gridLayout_2.addWidget(self.paramDataLineEdit, 1, 1, 1, 1)
        self.paramMarginsLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.paramMarginsLabel.setObjectName("paramMarginsLabel")
        self.gridLayout_2.addWidget(self.paramMarginsLabel, 5, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.paramCropMarginsXMin = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.paramCropMarginsXMin.setObjectName("paramCropMarginsXMin")
        self.horizontalLayout.addWidget(self.paramCropMarginsXMin)
        self.paramCropMarginsXMax = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.paramCropMarginsXMax.setObjectName("paramCropMarginsXMax")
        self.horizontalLayout.addWidget(self.paramCropMarginsXMax)
        self.paramCropMarginsYMin = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.paramCropMarginsYMin.setObjectName("paramCropMarginsYMin")
        self.horizontalLayout.addWidget(self.paramCropMarginsYMin)
        self.paramCropMarginsYMax = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.paramCropMarginsYMax.setObjectName("paramCropMarginsYMax")
        self.horizontalLayout.addWidget(self.paramCropMarginsYMax)
        self.gridLayout_2.addLayout(self.horizontalLayout, 5, 1, 1, 1)
        self.paramNumFrameLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.paramNumFrameLabel.setObjectName("paramNumFrameLabel")
        self.gridLayout_2.addWidget(self.paramNumFrameLabel, 2, 0, 1, 1)
        self.paramNumFrameLineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.paramNumFrameLineEdit.setObjectName("paramNumFrameLineEdit")
        self.gridLayout_2.addWidget(self.paramNumFrameLineEdit, 2, 1, 1, 1)
        self.paramCroppingCheckBox = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.paramCroppingCheckBox.setObjectName("paramCroppingCheckBox")
        self.gridLayout_2.addWidget(self.paramCroppingCheckBox, 4, 0, 1, 1)
        self.paramMarkingsLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.paramMarkingsLabel.setObjectName("paramMarkingsLabel")
        self.gridLayout_2.addWidget(self.paramMarkingsLabel, 6, 0, 1, 1)
        self.paramMarkingsLineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.paramMarkingsLineEdit.setObjectName("paramMarkingsLineEdit")
        self.gridLayout_2.addWidget(self.paramMarkingsLineEdit, 6, 1, 1, 1)
        self.paramSampleImagesButton = QtWidgets.QPushButton(self.markParamsTab)
        self.paramSampleImagesButton.setGeometry(QtCore.QRect(850, 70, 191, 41))
        self.paramSampleImagesButton.setObjectName("paramSampleImagesButton")
        self.paramGuiMarkButton = QtWidgets.QPushButton(self.markParamsTab)
        self.paramGuiMarkButton.setGeometry(QtCore.QRect(850, 150, 191, 41))
        self.paramGuiMarkButton.setObjectName("paramGuiMarkButton")
        self.paramCreateTrainingSetButton = QtWidgets.QPushButton(self.markParamsTab)
        self.paramCreateTrainingSetButton.setGeometry(QtCore.QRect(840, 220, 211, 51))
        self.paramCreateTrainingSetButton.setObjectName("paramCreateTrainingSetButton")
        self.markTabWidget.addTab(self.markParamsTab, "")
        self.markCheckTab = QtWidgets.QWidget()
        self.markCheckTab.setObjectName("markCheckTab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.markCheckTab)
        self.verticalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.checkGraphicsView = QtWidgets.QGraphicsView(self.markCheckTab)
        self.checkGraphicsView.setObjectName("checkGraphicsView")
        self.verticalLayout_3.addWidget(self.checkGraphicsView)
        self.checkFrameSlider = QtWidgets.QSlider(self.markCheckTab)
        self.checkFrameSlider.setOrientation(QtCore.Qt.Horizontal)
        self.checkFrameSlider.setObjectName("checkFrameSlider")
        self.verticalLayout_3.addWidget(self.checkFrameSlider)
        self.markTabWidget.addTab(self.markCheckTab, "")
        self.gridLayout.addWidget(self.markTabWidget, 0, 0, 1, 1)
        self.mainTabWidget.addTab(self.markTab, "")
        self.trainTab = QtWidgets.QWidget()
        self.trainTab.setObjectName("trainTab")
        self.mainTabWidget.addTab(self.trainTab, "")
        self.processTab = QtWidgets.QWidget()
        self.processTab.setObjectName("processTab")
        self.mainTabWidget.addTab(self.processTab, "")
        self.postprocessTab = QtWidgets.QWidget()
        self.postprocessTab.setObjectName("postprocessTab")
        self.mainTabWidget.addTab(self.postprocessTab, "")
        self.verticalLayout_2.addWidget(self.mainTabWidget)
        self.logTextEdit = QtWidgets.QTextEdit(self.centralWidget)
        self.logTextEdit.setMaximumSize(QtCore.QSize(16777215, 300))
        self.logTextEdit.setMouseTracking(True)
        self.logTextEdit.setReadOnly(True)
        self.logTextEdit.setObjectName("logTextEdit")
        self.verticalLayout_2.addWidget(self.logTextEdit)
        dlcgui.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(dlcgui)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1222, 29))
        self.menuBar.setObjectName("menuBar")
        dlcgui.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(dlcgui)
        self.mainToolBar.setObjectName("mainToolBar")
        dlcgui.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(dlcgui)
        self.statusBar.setObjectName("statusBar")
        dlcgui.setStatusBar(self.statusBar)

        self.retranslateUi(dlcgui)
        self.mainTabWidget.setCurrentIndex(0)
        self.markTabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(dlcgui)

    def retranslateUi(self, dlcgui):
        _translate = QtCore.QCoreApplication.translate
        dlcgui.setWindowTitle(_translate("dlcgui", "dlcgui"))
        self.pathsNetworkVideoLabel.setText(_translate("dlcgui", "Video folder"))
        self.pathsLocalButton.setText(_translate("dlcgui", "Open"))
        self.pathsLocalLabel.setText(_translate("dlcgui", "Local project folder"))
        self.pathsNetworkVideoButton.setText(_translate("dlcgui", "Open"))
        self.pathsImportButton.setText(_translate("dlcgui", "Open"))
        self.pathsImportLabel.setText(_translate("dlcgui", "Import project folder"))
        self.pathsImportPathsButton.setText(_translate("dlcgui", "Import paths"))
        self.markTabWidget.setTabText(self.markTabWidget.indexOf(self.markPathsTab), _translate("dlcgui", "paths"))
        self.paramSelectionLabel.setText(_translate("dlcgui", "Selection"))
        self.paramSelectionComboBox.setItemText(0, _translate("dlcgui", "uniform"))
        self.paramSelectionComboBox.setItemText(1, _translate("dlcgui", "k-means"))
        self.paramNameLabel.setText(_translate("dlcgui", "Marker Name"))
        self.paramDataLabel.setText(_translate("dlcgui", "Date"))
        self.paramMarginsLabel.setText(_translate("dlcgui", "Crop margins"))
        self.paramNumFrameLabel.setText(_translate("dlcgui", "Num Frames"))
        self.paramCroppingCheckBox.setText(_translate("dlcgui", "Cropping?"))
        self.paramMarkingsLabel.setText(_translate("dlcgui", "Markings"))
        self.paramSampleImagesButton.setText(_translate("dlcgui", "Sample Images"))
        self.paramGuiMarkButton.setText(_translate("dlcgui", "GUI: Mark"))
        self.paramCreateTrainingSetButton.setText(_translate("dlcgui", "Create Training Set"))
        self.markTabWidget.setTabText(self.markTabWidget.indexOf(self.markParamsTab), _translate("dlcgui", "params"))
        self.markTabWidget.setTabText(self.markTabWidget.indexOf(self.markCheckTab), _translate("dlcgui", "check"))
        self.mainTabWidget.setTabText(self.mainTabWidget.indexOf(self.markTab), _translate("dlcgui", "mark"))
        self.mainTabWidget.setTabText(self.mainTabWidget.indexOf(self.trainTab), _translate("dlcgui", "train"))
        self.mainTabWidget.setTabText(self.mainTabWidget.indexOf(self.processTab), _translate("dlcgui", "process"))
        self.mainTabWidget.setTabText(self.mainTabWidget.indexOf(self.postprocessTab), _translate("dlcgui", "postprocess"))

