# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/media/aleksejs/DataHDD/work/codes/image-analysis/behavioural/dlc-scripts/scripts/tools/ffmpeg_wrapper_gui/ffmpeg_wrapper/ffmpeg_wrapper.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_FFMPEG_WRAPPER(object):
    def setupUi(self, FFMPEG_WRAPPER):
        FFMPEG_WRAPPER.setObjectName("FFMPEG_WRAPPER")
        FFMPEG_WRAPPER.resize(952, 599)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(FFMPEG_WRAPPER.sizePolicy().hasHeightForWidth())
        FFMPEG_WRAPPER.setSizePolicy(sizePolicy)
        self.centralWidget = QtWidgets.QWidget(FFMPEG_WRAPPER)
        self.centralWidget.setObjectName("centralWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralWidget)
        self.horizontalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.mainModeComboBox = QtWidgets.QComboBox(self.centralWidget)
        self.mainModeComboBox.setObjectName("mainModeComboBox")
        self.mainModeComboBox.addItem("")
        self.mainModeComboBox.addItem("")
        self.mainModeComboBox.addItem("")
        self.verticalLayout_3.addWidget(self.mainModeComboBox)
        self.mainEncodingComboBox = QtWidgets.QComboBox(self.centralWidget)
        self.mainEncodingComboBox.setObjectName("mainEncodingComboBox")
        self.mainEncodingComboBox.addItem("")
        self.mainEncodingComboBox.addItem("")
        self.mainEncodingComboBox.addItem("")
        self.verticalLayout_3.addWidget(self.mainEncodingComboBox)
        self.mainGrayscaleCheckBox = QtWidgets.QCheckBox(self.centralWidget)
        self.mainGrayscaleCheckBox.setObjectName("mainGrayscaleCheckBox")
        self.verticalLayout_3.addWidget(self.mainGrayscaleCheckBox)
        self.mainLosslessCheckBox = QtWidgets.QCheckBox(self.centralWidget)
        self.mainLosslessCheckBox.setObjectName("mainLosslessCheckBox")
        self.verticalLayout_3.addWidget(self.mainLosslessCheckBox)
        self.frame = QtWidgets.QFrame(self.centralWidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.mainQuality1Label = QtWidgets.QLabel(self.frame)
        self.mainQuality1Label.setObjectName("mainQuality1Label")
        self.horizontalLayout.addWidget(self.mainQuality1Label)
        self.mainQuality2Label = QtWidgets.QLabel(self.frame)
        self.mainQuality2Label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.mainQuality2Label.setObjectName("mainQuality2Label")
        self.horizontalLayout.addWidget(self.mainQuality2Label)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.mainQualityCRFSlider = QtWidgets.QSlider(self.frame)
        self.mainQualityCRFSlider.setAutoFillBackground(True)
        self.mainQualityCRFSlider.setMaximum(51)
        self.mainQualityCRFSlider.setOrientation(QtCore.Qt.Horizontal)
        self.mainQualityCRFSlider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.mainQualityCRFSlider.setTickInterval(10)
        self.mainQualityCRFSlider.setObjectName("mainQualityCRFSlider")
        self.verticalLayout.addWidget(self.mainQualityCRFSlider)
        self.verticalLayout_3.addWidget(self.frame)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.mainSourceButton = QtWidgets.QPushButton(self.centralWidget)
        self.mainSourceButton.setMinimumSize(QtCore.QSize(200, 0))
        self.mainSourceButton.setObjectName("mainSourceButton")
        self.verticalLayout_4.addWidget(self.mainSourceButton)
        self.mainTargetButton = QtWidgets.QPushButton(self.centralWidget)
        self.mainTargetButton.setObjectName("mainTargetButton")
        self.verticalLayout_4.addWidget(self.mainTargetButton)
        self.mainConvertButton = QtWidgets.QPushButton(self.centralWidget)
        self.mainConvertButton.setObjectName("mainConvertButton")
        self.verticalLayout_4.addWidget(self.mainConvertButton)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        FFMPEG_WRAPPER.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(FFMPEG_WRAPPER)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 952, 29))
        self.menuBar.setObjectName("menuBar")
        FFMPEG_WRAPPER.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(FFMPEG_WRAPPER)
        self.mainToolBar.setObjectName("mainToolBar")
        FFMPEG_WRAPPER.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(FFMPEG_WRAPPER)
        self.statusBar.setObjectName("statusBar")
        FFMPEG_WRAPPER.setStatusBar(self.statusBar)

        self.retranslateUi(FFMPEG_WRAPPER)
        QtCore.QMetaObject.connectSlotsByName(FFMPEG_WRAPPER)

    def retranslateUi(self, FFMPEG_WRAPPER):
        _translate = QtCore.QCoreApplication.translate
        FFMPEG_WRAPPER.setWindowTitle(_translate("FFMPEG_WRAPPER", "FFMPEG_WRAPPER"))
        self.mainModeComboBox.setItemText(0, _translate("FFMPEG_WRAPPER", "--- select mode ---"))
        self.mainModeComboBox.setItemText(1, _translate("FFMPEG_WRAPPER", "Single Video"))
        self.mainModeComboBox.setItemText(2, _translate("FFMPEG_WRAPPER", "Folder Crawler"))
        self.mainEncodingComboBox.setItemText(0, _translate("FFMPEG_WRAPPER", "--- target encoding ---"))
        self.mainEncodingComboBox.setItemText(1, _translate("FFMPEG_WRAPPER", "AVI"))
        self.mainEncodingComboBox.setItemText(2, _translate("FFMPEG_WRAPPER", "MP4 (H265)"))
        self.mainGrayscaleCheckBox.setText(_translate("FFMPEG_WRAPPER", "Grayscale"))
        self.mainLosslessCheckBox.setText(_translate("FFMPEG_WRAPPER", "Lossless"))
        self.mainQuality1Label.setText(_translate("FFMPEG_WRAPPER", "Quality (CRF)"))
        self.mainQuality2Label.setText(_translate("FFMPEG_WRAPPER", "0"))
        self.mainSourceButton.setText(_translate("FFMPEG_WRAPPER", "Select Source"))
        self.mainTargetButton.setText(_translate("FFMPEG_WRAPPER", "Select Target"))
        self.mainConvertButton.setText(_translate("FFMPEG_WRAPPER", "Convert"))

